apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve
spec:
  replicas: 3
  selector:
    matchLables:
      app: kubeserve
    template:
      metadata:
        name: kubeserve
        lables:
          app: kubeserve
      spec:
        containers:
        - image: linuxacademycontent/kubeserve:v1
          name: app
