apiVersion: v1
kind: PersistentVolume
metadata:
  name: rc-deploy
  namespace: rc-daiichi
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/deploy/ipos-rc
    server: 20.203.162.8
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rc-deploy
  namespace: rc-daiichi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: rc-deploy