apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-test
  namespace: test01
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        command: ["nginx"]
        args: ["-g","daemon off", "-q"]
        ports:
        - containerPort: 80
