# apiVersion: v1
# kind: PersistentVolume
# metadata:
  # name: infra-discovery-rc
# spec:
  # capacity:
    # storage: 10Gi
  # accessModes:
    # - ReadWriteMany
  # persistentVolumeReclaimPolicy: Retain
  # mountOptions:
    # - hard
    # - nfsvers=4.1
  # nfs:
    # path: /nfs/deploy/ipos-rc/infra-discovery
    # server: 20.203.162.8
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
  # name: infra-discovery
# spec:
  # accessModes:
    # - ReadWriteMany
  # resources:
    # requests:
      # storage: 10Gi
# ---
apiVersion: v1
kind: Service
metadata:
  name: infra-discovery
  namespace: rc-daiichi
  labels:
    app: infra-discovery
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8761
    nodePort: 30003
    protocol: TCP
    name: infra-discovery
  selector:
    app: infra-discovery
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infra-discovery
  namespace: rc-daiichi
  labels:
    app: infra-discovery
spec:
  selector:
    matchLabels:
      app: infra-discovery
  serviceName: "infra-discovery"
  replicas: 1
  template:
    metadata:
      labels:
        app: infra-discovery
    spec:
      hostAliases:
        - ip: "20.203.162.250"
          hostnames:
          - "daiichi-rc.dxc.com"
      volumes:
      - name: infra-discovery
        persistentVolumeClaim:
          claimName: rc-deploy
      containers:
      - name: infra-discovery
        image: ec2-52-220-108-251.ap-southeast-1.compute.amazonaws.com:443/ttran270:ipos-2.0
        imagePullPolicy: IfNotPresent
        env:
          - name: HOST
            value: "daiichi-rc.dxc.com"
          - name: IPOS_SERVICE
            value: "infra-discovery"
        command: ["/bin/sh"]
        args: ["-c", "openssl s_client -showcerts -connect $HOST:443 -servername $HOST  </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > $HOST.pem; openssl x509 -inform PEM -in $HOST.pem -outform DER -out $HOST.cer; keytool -import -alias $HOST -keystore /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts -file $HOST.cer -storepass changeit -noprompt; cd $IPOS_SERVICE; java -jar *.jar"]
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
        volumeMounts:
        - mountPath: "/home/ipos"
          name: infra-discovery
        securityContext:
          privileged: true
        livenessProbe:
          tcpSocket:
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 8761
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      imagePullSecrets:
      - name: regcred