apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-0
  namespace: rc-daiichi
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/data-rc/elasticsearch-0
    server: 20.203.162.8
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-1
  namespace: rc-daiichi
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/data-rc/elasticsearch-1
    server: 20.203.162.8
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-elasticsearch-0
  namespace: rc-daiichi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-elasticsearch-1
  namespace: rc-daiichi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi