apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: db
spec:
  replicas: 2
  selector:
    matchLabels: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
  spec:
    containers:
      - name:: elasticsearch
      image: elasticsearch:7.5.0