# apiVersion: v1
# kind: PersistentVolume
# metadata:
  # name: web-agent-rc
  # namespace: rc-daiichi
# spec:
  # capacity:
    # storage: 10Gi
  # accessModes:
    # - ReadWriteMany
  # persistentVolumeReclaimPolicy: Retain
  # mountOptions:
    # - hard
    # - nfsvers=4.1
  # nfs:
    # path: /nfs/deploy/ipos-rc/web-agent
    # server: 20.203.162.8
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
  # name: web-agent
  # namespace: rc-daiichi
# spec:
  # accessModes:
    # - ReadWriteMany
  # resources:
    # requests:
      # storage: 10Gi
# ---
apiVersion: v1
kind: Service
metadata:
  name: web-agent
  namespace: rc-daiichi
  labels:
    app: web-agent
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 18080
    protocol: TCP
    name: web-agent
  selector:
    app: web-agent
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-agent
  namespace: rc-daiichi
  labels:
    app: web-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-agent
    spec:
      volumes:
      - name: web-agent
        persistentVolumeClaim:
          claimName: rc-deploy
      hostAliases:
        - ip: "20.203.162.250"
          hostnames:
          - "daiichi-rc.dxc.com"
      containers:
      - name: web-agent
        image: ec2-52-220-108-251.ap-southeast-1.compute.amazonaws.com:443/ttran270:ipos-2.0
        imagePullPolicy: IfNotPresent
        env:
          - name: HOST
            value: "daiichi-rc.dxc.com"
          - name: IPOS_SERVICE
            value: "web-agent"
        command: ["/bin/sh"]
        args: ["-c", "openssl s_client -showcerts -connect $HOST:443 -servername $HOST  </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > $HOST.pem; openssl x509 -inform PEM -in $HOST.pem -outform DER -out $HOST.cer; keytool -import -alias $HOST -keystore /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts -file $HOST.cer -storepass changeit -noprompt; cd $IPOS_SERVICE; java -jar *.jar"]
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
        volumeMounts:
        - mountPath: "/home/ipos"
          name: web-agent
        securityContext:
          privileged: true
        livenessProbe:
          tcpSocket:
            port: 18080
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 18080
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
      imagePullSecrets:
      - name: regcred
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-agent
  namespace: rc-daiichi
  annotations:
    nginx.ingress.kubernetes.io/app-root: /ife-web-base-agent
spec:
  tls:
  - hosts:
    - daiichi-rc.dxc.com
    secretName: daiichi-rc
  rules:
    - host: daiichi-rc.dxc.com
      http:
        paths:
        - backend:
            serviceName: web-agent
            servicePort: 80
          path: /ife-web-base-agent